name = "backend"
compatibility_date = "2024-07-31"

 [vars]
 DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzRhNWQ1NzYtZjI4My00NDZmLWJlYWYtNzQyNzA3YzY2MmNjIiwidGVuYW50X2lkIjoiZjFlYzQxMDEwYTg0MjAzMmZmOGRmZDE3NmIxMzZlMzM1NWZlN2NiMzIyYmY5NDZlZjM4ZDZlNWRmMzk0NmQ3ZCIsImludGVybmFsX3NlY3JldCI6IjRiZDg0ZmEwLWIxMDgtNDRhYy04NGFlLTNlMDM3NmU2Zjg4ZSJ9.t7fDp8PH5rcldgcASfYMy2tEGGlU3KC_k92-K2ca1VM "

JWT_SECRET = "asdfdsg"